export const ChatEvents = {
  RoomJoin: 'room.join',
  RoomLeave: 'room.leave',
  RoomRead: 'room.read',
  RoomReadUpdated: 'room.read.updated',
  MessageSend: 'message.send',
  MessageCreated: 'message.created',
  MessageEdit: 'message.edit',
  MessageUpdated: 'message.updated',
  MessageDelete: 'message.delete',
  MessageDeleted: 'message.deleted',
  MessageReactAdd: 'message.react.add',
  MessageReactRemove: 'message.react.remove',
  MessageReacted: 'message.reacted',
  TypingStart: 'typing.start',
  TypingStop: 'typing.stop',
  TypingUpdated: 'typing.updated',
  ChatError: 'chat.error',
} as const;
